services:
  - type: web
    name: ai-image-classifier
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run main.py --server.port $PORT --server.address 0.0.0.0"
